### ISSUE TITLE
how to use this script

### ISSUE THREAD

**Issue by claudianavital** [samarthshrivas/Slowed-Reverbed-Surround#1]
hello can you please explain how to use this script in python,, i clone into my pc installed ffmpeg also installed requirements file.... now what to do please how to import script how to import music and get output of file

**Comment by samarthshrivas** [comment]
Apologies for not mentioning it straight.
#### First git clone install ffmpeg and requirements file
```
git clone https://github.com/samarthshrivas/Slowed-Reverbed-Surround
cd Slowed-Reverbed-Surround
pip install -r requirements.txt
```

#### than go into utils dir

`cd utils`
Here create file test.py
```
# test.py

from utils import slowedreverb
slowedreverb('input.wav', 'output.wav')
```

## Here is a Example for File Paths
https://github.com/samarthshrivas/Slowed-Reverbed-Surround/tree/main/example

**Comment by cuteseerat** [comment]
thank you for instant reply but still face some problem 


C:\Users\jaska\Slowed-Reverbed-Surround\utils>import test
'import' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\jaska\Slowed-Reverbed-Surround\utils>python
Python 3.11.3 (tags/v3.11.3:f3909b8, Apr  4 2023, 23:49:59) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import test.py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jaska\Slowed-Reverbed-Surround\utils\test.py", line 4, in <module>
    slowedreverb('Sahan.wav', 'Sahanlofi.wav')
  File "C:\Users\jaska\Slowed-Reverbed-Surround\utils\utils.py", line 28, in slowedreverb
    effected = board(audio, sample_rate)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: More than two channels received!
>>>

**Comment by claudianavital** [comment]
thank you so much explaining all now it is working
